# Note that using yaml config files requires the optional dependency PyYAML.
onedrive:
    tenant_id:  # required
    client_id:  # required
    client_secret_value:  # required
    redirect_url: http://localhost:8080  # optional, line can be removed
    refresh_token: null  # optional, line can be removed
